FROM python:3.12-slim

# Install ClustalW2 and its dependencies.
# We use clustalw2 as it's the more modern version often found in repositories.
# `apt update` refreshes the package list.
# `apt install -y` installs the package without prompting for confirmation.
# `rm -rf /var/lib/apt/lists/*` cleans up the apt cache to keep the image size small.
RUN apt update && \
    apt install -y clustalw && \
    rm -rf /var/lib/apt/lists/*

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

# Copy the application into the container.
COPY . /app

# Install the application dependencies.
WORKDIR /app
RUN uv sync --frozen --no-cache

# Expose the port your application will listen on.
EXPOSE 80

# Run the application.
CMD ["/app/.venv/bin/fastapi", "run", "app/main.py", "--port", "80", "--host", "0.0.0.0"]